### ISSUE TITLE
Adyen 8 | Force the **Save Credit Card** checkbox to be checked in checkout with subscription in cart

### ISSUE THREAD

**Issue by chrismshea** [subscribepro/subscribepro-magento2-adyen#12]
When checking out with a new card.  The customer has the option to select/unselect a checkbox to save the card.
When there is a subscription item in the cart the box should be selected, and unable to be unselected.
![Checkout_Adyen_NewCard](https://github.com/subscribepro/subscribepro-magento2-adyen/assets/1232258/8f5d0f53-f320-4d1e-a537-054c2cf8ecd9)

**Comment by czettnersandor** [comment]
Please see PR: https://github.com/subscribepro/subscribepro-magento2-adyen/pull/16

Just a note, the adyen.js is minified and I could not read it easily. This set of mixins are extending the JS that are fully available. I don't think the previous solution for Adyen 7 worked, because the state data is not passed to the frontend at all from the backend. It's only saved to the sessionStorage. Now the checkbox is selected by default and can not untick it if there's an active subscription in the cart.
