### ISSUE TITLE
Adyen 8 | Display Adyen CC payment method when checking out with subscription

### ISSUE THREAD

**Issue by chrismshea** [subscribepro/subscribepro-magento2-adyen#9]
I have the module enabled, and the adyen payment method is configured to be allowed, but it is not displayed in checkout.

![adyen_allowed](https://github.com/subscribepro/subscribepro-magento2-adyen/assets/1232258/ab75f264-e86a-4933-9a9d-4e09b526c157)
![adyen_missing](https://github.com/subscribepro/subscribepro-magento2-adyen/assets/1232258/207a4da1-a041-4e21-a561-95b7c31ee7da)

**Comment by czettnersandor** [comment]
Please see these two PRs:
https://github.com/subscribepro/subscribepro-magento2-adyen/pull/11
https://github.com/subscribepro/subscribepro-magento2-ext/pull/195

I added some debug logs to help easier debugging. There was an actual bug in AdyenCcDataAssignObserver that I corrected and also in the main extension, selecting a website scope to make a connection filled swarming_subscribepro/third_party_payment/allowed_method config value with an empty string. It's a Magento bug and happens when you make the multiselect depend on another field. I removed this dependency, but check your local installation.

With these changes, a payment profile is saved correctly to the platform.

When making an order from the subscribepro platform, it fails with "paymentMethod" missing, which is likely an issue with Adyen, but I'm investigating.
